name: skg
recipe: drupal11
env_file:
  - .env

config:
  webroot: web
  php: "8.3"
  composer_version: 2.9.1

services:
  appserver:
    scanner:
      retry: 5
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: "/app/web"
        DRUSH_OPTIONS_URI: "https://skg.lndo.site"

  database:
    creds:
      user: drupal
      password: drupal
      database: drupal

  fe-node:
    type: node
    app_mount: disabled
    ovverides:
      volumes:
        - ./src/frontend:/app:delegated
      working_dor: /app
      environment:
        DOCKER_LOCAL: 1
      command: bash -c 'npm install && npm run dev'

tooling:
  drush:
    service: appserver
  composer:
    service: appserver
  update-settings:
    service: appserver
    cmd: "cp -f src/settings/settings.php web/sites/default/settings.php"
