name: skg
recipe: drupal11
env_file:
  - .env

config:
  webroot: web
  php: "8.3"
  composer_version: 2.9.1

services:
  appserver:
    scanner:
      retry: 5
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: "/app/web"
        DRUSH_OPTIONS_URI: "https://skg.lndo.site"

  database:
    creds:
      user: drupal
      password: drupal
      database: drupal

  fe-node:
    type: node:20
    app_mount: disabled
    scanner:
      retry: 5
    overrides:
      volumes:
      - ./src/frontend:/app:delegated
      working_dir: /app
      environment:
        DOCKER_LOCAL: 1
      command: bash -c "npm install && npm run dev"

  watcher-node:
    type: node:20
    app_mount: disabled
    scanner:
      retry: 5
    overrides:
      volumes:
      - ./:/app:delegated
      working_dir: /app
      environment:
        DOCKER_LOCAL: 1
      command: bash -c "npm install && npm run dev"

tooling:
  drush:
    service: appserver
  composer:
    service: appserver
  update-settings:
    service: appserver
    cmd: "cp -f src/settings/settings.php web/sites/default/settings.php"
